from DataLoader_ey import createDataframeForDB
import sqlite3 as sql

con = sql.connect('database.db')
c = con.cursor()
#create_query ='CREATE TABLE applicants (id INT, balance TEXT,duration INT,history TEXT,purpose TEXT,amount REAL,savings TEXT,employment TEXT,available_income TEXT,other_debtors TEXT,residence TEXT,assets TEXT,age INT,other_loans TEXT,housing TEXT,previous_loans TEXT,job TEXT,people_liable TEXT,telephone TEXT, NN_recommendation TEXT, NN_confidence REAL)'
#c.execute(create_query)
#con.commit()
df = createDataframeForDB()
df.to_sql('applicants', con, index_label = 'id', if_exists="replace")
c.execute('ALTER TABLE applicants RENAME COLUMN balance_ TO balance;')
c.execute('ALTER TABLE applicants RENAME COLUMN duration_ TO duration;')
c.execute('ALTER TABLE applicants RENAME COLUMN history_ TO history;')
c.execute('ALTER TABLE applicants RENAME COLUMN purpose_ TO purpose;')
c.execute('ALTER TABLE applicants RENAME COLUMN amount_ TO amount;')
c.execute('ALTER TABLE applicants RENAME COLUMN savings_ TO savings;')
c.execute('ALTER TABLE applicants RENAME COLUMN employment_ TO employment;')
c.execute('ALTER TABLE applicants RENAME COLUMN available_income_ TO available_income;')
c.execute('ALTER TABLE applicants RENAME COLUMN other_debtors_ TO other_debtors;')
c.execute('ALTER TABLE applicants RENAME COLUMN residence_ TO residence;')
c.execute('ALTER TABLE applicants RENAME COLUMN assets_ TO assets;')
c.execute('ALTER TABLE applicants RENAME COLUMN other_loans_ TO other_loans;')
c.execute('ALTER TABLE applicants RENAME COLUMN housing_ TO housing;')
c.execute('ALTER TABLE applicants RENAME COLUMN previous_loans_ TO previous_loans;')
c.execute('ALTER TABLE applicants RENAME COLUMN job_ TO job;')
c.execute('ALTER TABLE applicants RENAME COLUMN people_liable_ TO people_liable;')
c.execute('ALTER TABLE applicants RENAME COLUMN telephone_ TO telephone;')
con.close()
